"use client";

import React from "react";
import { Scale } from "lucide-react";

export default function TermsAndConditions() {
  return (
    <div className="max-w-4xl mx-auto px-6 py-12 md:py-20 flex-1 flex flex-col gap-10 text-left">
      <div className="space-y-4 max-w-2xl border-b border-white/5 pb-8">
        <div className="inline-flex items-center gap-1.5 text-xs text-sky-400 font-semibold tracking-wider uppercase">
          <Scale className="w-4.5 h-4.5" /> Legal Disclosures
        </div>
        <h1 className="text-3xl sm:text-5xl font-extrabold tracking-tight" style={{ fontFamily: "'Instrument Serif', serif" }}>
          Terms & Conditions
        </h1>
        <p className="text-xs text-muted-foreground">Last updated: July 30, 2026</p>
      </div>

      <div className="space-y-6 text-xs text-muted-foreground leading-relaxed">
        <h3 className="text-sm font-bold text-white uppercase tracking-wider">1. No Legal Advice</h3>
        <p>
          The analysis generated by the AI Eligibility Checker and the templates produced by the AI Legal Draft Generator are for informational and preparatory assistance only. They do not constitute formal legal representation. Applications must be reviewed and filed by certified legal counsel.
        </p>

        <h3 className="text-sm font-bold text-white uppercase tracking-wider">2. Account Responsibility</h3>
        <p>
          NGO representatives, advocates, and jail officers are responsible for ensuring that all information entered is accurate relative to official case registries and physical jail logs.
        </p>

        <h3 className="text-sm font-bold text-white uppercase tracking-wider">3. Consensus Network Fees</h3>
        <p>
          bilblock subsidizes consensus transaction logging costs on the Hedera node network. We reserve the right to cap maximum block operations per account in cases of network congestion.
        </p>
      </div>
    </div>
  );
}
